[window]
opacity=0.85
padding={x=8,y=4}

[selection]
save_to_clipboard=true

[[keyboard.bindings]]
key='Insert'
mods='Control'
action='Copy'

[[keyboard.bindings]]
key='Insert'
mods='Shift'
action='Paste'
